nebula-contrib/ngbatis

- .github/workflows/maven-publish.yml
- README.md
- pom.xml
> Add github action workflow

- README-CN.md
> i18n for README

- nebula_java_style_checks.xml
- ngbatis-demo/nebula_java_style_checks.xml
- ngbatis-demo/pom.xml
- pom.xml
Add style check for java code in order to keep our code specification consistent
@CorvusYe please reformat the ngbatis's code, sorry for the increased workload.
> add java checkstyle

- src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/KvFn.java
- src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java
get Column.class name field value, to replace the original field
for example: 
@Column(name = "id_no")
private String idNo;
> get Column.class name field value, to replace the original 

- src/main/java/org/nebula/contrib/ngbatis/NgbatisContextInitializer.java
> feat: 使用springcloud及nacos配置中心初始化失败问题

- pom.xml
- src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java
Ideas come from: https://github.com/nebula-contrib/ngbatis/issues/73
> enhanced: NebulaDaoBasic default impls can be overwritten by xml

- ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
- pom.xml
- src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
- src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
- src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java
- src/main/resources/NebulaDaoBasic.xml
> add upsert tag/edge function

- CHANGELOG.md
- CONTRIBUTING-CN.md
- CONTRIBUTING.md
- pom.xml
- src/main/java/org/nebula/contrib/ngbatis/NgbatisBeanFactoryPostProcessor.java
- src/main/java/org/nebula/contrib/ngbatis/NgbatisContextInitializer.java
- src/main/java/org/nebula/contrib/ngbatis/SessionDispatcher.java
- src/main/java/org/nebula/contrib/ngbatis/annotations/Space.java
- src/main/java/org/nebula/contrib/ngbatis/config/NgbatisConfig.java
- src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
- src/main/java/org/nebula/contrib/ngbatis/models/MapperContext.java
- src/main/java/org/nebula/contrib/ngbatis/session/IntervalCheckSessionDispatcher.java
- feat: Init the session pool which space is declared in xml method tag.
- standard: add contributing.
- upgrade: nebula-java 3.3.0->3.4.0 #134
> nebula-java upgrade 3.3.0->3.4.0 (#134) | add contributin | refact session pool function.

- .github/workflows/doc_en.yaml
- .gitignore
- docs/en/md/dev-example/custom-crud.md
- docs/en/md/dev-example/parameter-use.md
- docs/en/md/dev-example/prepare.md
- docs/en/md/dev-example/result.md
- docs/en/md/quick-start/features.md
> feat: add en docs via gh pages

- .github/workflows/release.yml
- .github/workflows/snapshot.yaml
Sorry I used a made-up argument by ai agent, this one is valid.
> fix maven_args in action-maven-publish@v1

- .github/workflows/release.yml
- .github/workflows/snapshot.yaml
close: #227
ref: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md
> ci: fix publishing ci

- docs/en/md/step-forward-docs/operation-sequence.md
Issue Link: #226 
Added the translated content of EXECUTION-PROCESS.md to operation-sequence.md
> add EXECUTION-PROCESS.md to docs

- CHANGELOG.md
- pom.xml
- src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/IncludeFn.java
- src/main/java/org/nebula/contrib/ngbatis/handler/NgPathResultHandler.java
- src/main/java/org/nebula/contrib/ngbatis/handler/NgVertexResultHandler.java
- src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
- src/main/java/org/nebula/contrib/ngbatis/models/NgqlModel.java
- src/main/java/org/nebula/contrib/ngbatis/models/data/NgPath.java
- src/main/java/org/nebula/contrib/ngbatis/models/data/NgTriplet.java
- src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
- beetl: 3.1.8-RELEASE -> 3.15.10.RELEASE
- antlr4: 4.7.2 -> 4.11.1
fix: https://github.com/nebula-contrib/ngbatis/issues/252
> use antlr 4.11.1, beetl 3.15.10

- .github/workflows/release.yml
> ci: fix mvn deploy gpg signing

- src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
> fix: style check

- CHANGELOG.md
- README-CN.md
- README.md
- ngbatis-demo/pom.xml
- pom.xml
- src/main/java/org/nebula/contrib/ngbatis/exception/QueryException.java
- src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
The error code of the `ResultSet` is returned in order to deal with the error message 
on the calling side in accordance with the application situation.
> fix: complete the error code of ResultSet into QueryException.

- ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
- src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
- src/main/resources/NebulaDaoBasic.xml
1、新增查看所有空间showSpaces方法
3、提供使用showSpaces方法的单元测试
> feat: add showSpaces function

- CHANGELOG.md
- src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
允许在没有 mapper.xml 的情况下，正常启动服务器。
PR type:
> fix: allow normal startup without any mapper files.

- src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
- optimized  `showSpaces` method code and  related code format
> code optimization

- src/main/java/org/nebula/contrib/ngbatis/annotations/base/GraphId.java
- src/main/java/org/nebula/contrib/ngbatis/base/GraphBaseExt.java
- src/main/java/org/nebula/contrib/ngbatis/binding/DefaultResultResolver.java
- src/main/java/org/nebula/contrib/ngbatis/enums/Direction.java
- src/main/java/org/nebula/contrib/ngbatis/enums/IdType.java
- src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
> fix code style check

- src/main/java/org/nebula/contrib/ngbatis/base/GraphBaseExt.java
> feat: supporting SessionPool calls for direct data query.

- ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoOrderedTests.java
- ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
- src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
- src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasicExt.java
- src/main/resources/NebulaDaoBasic.xml
- Please pay attention to whether `startNodes` , `endNodes`, `listEndNodes` and `listStartNodes` are used in the project.
Pay attention to whether the repair work has a negative impact on actual usage
- 请留意项目中是否使用了 `listEndNodes` and `listStartNodes` 两个接口
注意当前修复工作是否为实际使用情况带来负面影响。
feat: add methods: `insertForce(v)` `insertSelectiveForce(v)`
fix: #329 , #324
> fix#329 #324: correct the return value type and clear the interface generic. and add 2 methods.

- .github/workflows/pull_request.yml
- CHANGELOG-CN.md
- CHANGELOG.md
- README-CN.md
- README.md
- ngbatis-demo/pom.xml
- ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TestRepository.java
- ngbatis-demo/src/main/resources/mapper/TestRepository.xml
- ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
- pom.xml
- src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/ValueFmtFn.java
- src/main/java/org/nebula/contrib/ngbatis/session/SpaceRouter.java
fix: https://github.com/nebula-contrib/ngbatis/issues/339
> fix: `ng.valueFmt(v)` cannot output `null` as a placeholder when v is null.

- pom.xml
- src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxyClassGenerator.java
Automatically use ASM to generate values for stacks and local variables in proxy classes, fixed the stackoverflow issue.
> fix #63: automatically calculating stack and local variables in asm

- CHANGELOG-CN.md
- CHANGELOG.md
- ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/TestGeo.java
- ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TestGeoDao.java
- ngbatis-demo/src/main/resources/mapper/TestGeoDao.xml
- ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/TestGeoDaoTest.java
- src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/ValueFmtFn.java
- src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java
db type | java type
---|---
geo(point) | org.springframework.data.geo.Box
geo(linestring) | org.springframework.data.geo.Point
geo(polygon) | org.springframework.data.geo.Polygon
geo | Object
<details>
<summary><h4>中文</h4></summary>
- 支持Geo类型（点、线、面）
字段类型 | 属性类型
---|---
geo(point) | org.springframework.data.geo.Box
geo(linestring) | org.springframework.data.geo.Point
geo(polygon) | org.springframework.data.geo.Polygon
geo | Object
</details>
> feat: Supporting geometry types.
