src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java

If the space in the session is the same as which used by the dao method,
ngbatis will not **switch the spaces** [`USE space`] again.
So need to print the current space in the console for debugging.

enhanced: #64 [debug log] print current space in session before switch

---

src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

@llinzhe
When switch space is required, will execute twice , 
one is `USE space` , another is normal nGQL

fix #78 use space and gql are executed together incorrect in 3.3.0

---

.github/workflows/pull_request.yml
CHANGELOG.md
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TestRepository.java
ngbatis-demo/src/main/resources/mapper/TestRepository.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NgbatisDemoApplicationTests.java
src/main/java/org/nebula/contrib/ngbatis/handler/AbstractResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/CollectionNgEdgeResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/CollectionNgPathResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/CollectionNgSubgraphResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/CollectionNgVertexResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/NgEdgeResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/NgPathResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/NgSubgraphResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/NgVertexResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/models/data/NgEdge.java
src/main/java/org/nebula/contrib/ngbatis/models/data/NgPath.java
src/main/java/org/nebula/contrib/ngbatis/models/data/NgSubgraph.java
src/main/java/org/nebula/contrib/ngbatis/models/data/NgVertex.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java
src/main/resources/NebulaDaoBasic.xml

- feat: provide default data structure for edge \ vertex \ path \ sub-graph, and their result handler. #103 #118
for example: 
```java
List<NgSubgraph<String>> selectSubgraph();
```
```xml
<select id="selectSubgraph" resultType="org.nebula.contrib.ngbatis.models.data.NgSubgraph">
GET SUBGRAPH WITH PROP 3 STEPS FROM "startVid"
BOTH like
YIELD VERTICES AS nodes, EDGES AS relationships
</select>
```
> ##  **alias must be nodes and relationship.**
- feat: NebulaDaoBasic shortest path support. #118
```java
List<NgPath<String>> ngPaths = dao.shortestPath("startId", "endId");
```

feat #103 #118 support. provide default data structure for edge \ vertex \ path \ sub-graph, and their result handler.

---

CHANGELOG.md
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Employee.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/EmployeeDao.java
ngbatis-demo/src/main/resources/mapper/EmployeeDao.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/EmployeeDaoTest.java
src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/KvFn.java
src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/TagNameFn.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java
src/main/resources/NebulaDaoBasic.xml

- fix: when vertex has multi tags cannot set value properly.[#120](https://github.com/nebula-contrib/ngbatis/issues/120) 
- If an entity type is another entity type's super class, all attribute are being required in database schema except `@Transient`
> 如果一个实体类是另一个实体类的父类，则其所有除了注解`@Transient` 了的属性，都需要在数据库中声明。
- `NebulaDaoBasic#insert`、`NebulaDaoBasic#insertSelective`、`NebulaDaoBasic#insertBatch` can create an multi tags vertex, when the param has super class. Such as [Employee.java](/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Employee.java)
cc: @LiuTianyou
What we talk about the column forward marking in #39 has been changed.
In this version, super type entity didn't need forward marking anymore. 
```diff
- When the field in super class we …
```

fix: #120 and new feat: multi tags support.

---

CHANGELOG.md
ngbatis-demo/pom.xml
pom.xml

- If an entity type is another entity type's super class, all attribute are being required in database schema except `@Transient`
> 如果一个实体类是另一个实体类的父类，则其所有除了注解`@Transient` 了的属性，都需要在数据库中声明。
- fix: when vertex has multi tags cannot set value properly.[#120](https://github.com/nebula-contrib/ngbatis/issues/120) 
- fix: `ng.join` bug [#122](https://github.com/nebula-contrib/ngbatis/issues/122)
- feat: multi tags support for vertex inserting.
- feat: provide default data structure for edge \ vertex \ path \ sub-graph, and their result handler. #103 #118
- feat: NebulaDaoBasic shortest path support. #118
- feat: ng.valueFmt support escape ( default true ). Use `ValueFmtFn.setEscape( false );` to disable this feature.
- feat: add config to use `nebula-java` session pool
```
nebula:
ngbatis: …
```

release: 1.1.2-SNAPSHOT -> 1.1.2

---

src/main/java/org/nebula/contrib/ngbatis/NgbatisBeanFactoryPostProcessor.java

Description: 
We enabled `sessionPool` in the previous version through `nebula.ngbatis.use-session-pool: true`
but when developers set the configuration `nebula.space` in yml only instead of in xml, 
the session pool was not initialized during the startup process.

fix: sessionPool is null when the space name only declared in yml

---

src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java

Ngbatis will check the current space before each execution 
and help developers complete automatic switching. 
But it did not capture error information, which makes it difficult for developers to report an error in this statement.
Such as: 
Some typo mistake happend when setting the default space, The `Space was not chosen` message make developers confuse.
Reported in #150

fix: make the error message clearer when 'use space' failed

---

CHANGELOG.md
README-CN.md
README.md
ngbatis-demo/pom.xml
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/TimeTest.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TimeTestDao.java
ngbatis-demo/src/main/resources/mapper/TimeTestDao.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NgbatisDemoApplicationTests.java
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/TimeTestDaoTest.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/binding/DefaultArgsResolver.java
src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/ValueFmtFn.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

- When a field is declared by java.util.Date, it is no longer allowed to set a value using Timestamp
> 当字段由java.util.Date声明时，不再允许使用java.sql.Timestamp设值
- fix: data error for date type in the database.[#102](https://github.com/nebula-contrib/ngbatis/issues/102)
- Clear time type mapping.
db type | java type
---|---
datetime | java.util.Date
date | java.sql.Date
time | java.sql.Time
timestamp | java.sql.Timestamp
duration | java.time.Duration

fix: #102 and clear time type mapping (v1.1.4)

---

ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/IfStringLike.java
src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/ValueFmtFn.java

Single quote are not within the scope of StringEscapeUtils.escapeJava escape, 
and double quote are enabled as delimiters for string parameters to avoid the above issues. 
If you still want to use the original single quote due to special processing in the project, 
you can use `ValueFmtFn.setParameterQuote ("'");` to preserve the original usage.
---
单引号不在 StringEscapeUtils.escapeJava 转义的范围内，
启用双引号来作为字符串参数的界定符，从而规避上述问题。
如果项目中因为特殊的处理依然想用原来的单引号，
可用 ValueFmtFn.setParameterQuote("'"); 来保留原用法。

fix: #176 use double quote instead of the original single quote in valuaFmt function

---

CHANGELOG.md
README-CN.md
README.md
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/TimeTestDaoTest.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/binding/DateDeserializer.java
src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/ValueFmtFn.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java
src/test/java/org/nebula/contrib/ngbatis/binding/DateDeserializerTest.java

- Change the time format from `yyyy-MM-dd'T'HH:mm:ss.sss` to `yyyy-MM-dd'T'HH:mm:ss.SSS`
- When converting `Date`, read microsec from `DateTimeWrapper` and change to millisec
PR type

fix #185: improve the accuracy of datetime to milliseconds (v1.1.5)

---

CHANGELOG.md
pom.xml
src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
src/main/java/org/nebula/contrib/ngbatis/models/MethodModel.java

- nebula-java: 3.5.0 -> 3.6.0
- fix: when DAO/Mapper method has `Page` type param with `@Param`, the param name can not be use. 
> 如原来项目中分页相关接口，用了不起作用的 `@Param`, 但 xml 还是使用 p0, p1... 
> 需要将 `@Param` 移除，或者将 xml 中的参数名改成 注解的参数名，以保证参数名统一
PR type:

fix: when DAO/Mapper method has `Page` type param with `@Param`, the param name can not be use. 

---

.github/workflows/doc_en.yaml

the upstream vitepress change breaks the build
now stick to a working version first

quickfix: ngbatis doc quick broken build

---

.github/workflows/release.yml
.github/workflows/snapshot.yaml

I don't know why recent mvn CI failed due to javadoc failures, it's strange that it was not triggered before though.
Let's explicitly skip it.

ci: skip javadoc in maven publish

---

.github/workflows/release.yml
.github/workflows/snapshot.yaml

ref: 
- https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md
- https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven
close: #223
Let's see how this works now, We don't need the archived action [here](https://github.com/samuelmeuli/action-maven-publish) now

ci drop old gh action, use mvn directly

---

pom.xml
src/main/java/org/nebula/contrib/ngbatis/handler/NgPathResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/handler/NgVertexResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/models/data/NgPath.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java

改造路径查询，路径对象中带有edge属性和vertex实体+vertex属性，经过测试，无需修改daoBasic任何代码，兼容已有代码

Extending NgPath

---

.github/workflows/doc_en_pull_request_dryrun.yaml

I just realized the dryrun action will wipe the github page, sorry for this.
I just had to manually rerun the vitepress job to bring the en docs back.
- dryrun only happened in pr before merge
- removed the wrong step, this will wipe the pages
ref:
1. opened: A new pull request is created.
2. synchronize: The pull request's branch is updated with new commits.
3. reopened: A closed pull request is reopened.

fix: ci not setting up pages in doc dryrun

---

ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
src/main/resources/NebulaDaoBasic.xml

According to https://github.com/nebula-contrib/ngbatis/issues/234#issue-1916633019   #234 
add insertEdgeBatch function
include:
- test module
- reformat `src/main/resources/NebulaDaoBasic.xml` 
cc @CorvusYe Thank you!

Feat: add insertEdgeBatch function #234

---

ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
src/main/resources/NebulaDaoBasic.xml

- add my personal information to `pom.xml`
- add add deleteByIdBatch interface function
- add relative test module

feat: add deleteByIdBatch interface and my information

---

.github/workflows/doc_en.yaml

it seems github page wiping will still be triggered even after we have the ignore dot file, now let's force Vitepress being built for all merged PR to protect the github page

ci: remove file scope of vitepress

---

CHANGELOG.md
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/DropSpaceDao.java
ngbatis-demo/src/main/resources/mapper/DropSpaceDao.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/DropSpaceDaoTest.java
src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java

```xml
<mapper namespace="...">
<create id="createSpace" space="null">
create space new_space ( vid_type  = INT64 );
</create>
</mapper>
```

fix: support methods in mapper tags to set space to null.

---

CHANGELOG.md
README.md
ngbatis-demo/pom.xml
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/DropSpaceDao.java
ngbatis-demo/src/main/resources/mapper/DropSpaceDao.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/DropSpaceDaoTest.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java

- nebula-java: 3.5.0 -> 3.6.0
- beetl: 3.1.8-RELEASE -> 3.15.10.RELEASE
- antlr4: 4.7.2 -> 4.11.1
- feat: support `<nGQL>` include query pieces. ([#212](https://github.com/nebula-contrib/ngbatis/pull/212), via [dieyi](https://github.com/1244453393))
- feat: extending `NgPath`, when 'with prop' is used in nGQL, edge attributes can be obtained from NgPath. ([#228](https://github.com/nebula-contrib/ngbatis/pull/228), via [dieyi](https://github.com/1244453393))
- feat: expanding the `insertEdgeBatch` interface in `NebulaDaoBasic`. ([#244](https://github.com/nebula-contrib/ngbatis/pull/244), via [Sunhb](https://github.com/shbone))
- feat: expanding the `deleteByIdBatch` interface in `NebulaDaoBasic`. ([#247](https://github.com/nebula-contrib/ngbatis/pull/244), via …

v1.2.0-beta

---

CHANGELOG.md
CONTRIBUTING.md
ngbatis-demo/pom.xml
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/ColumnAlias.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Employee.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Like.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/LikeWithRank.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/NoPropertiesVertex.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Person.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/TimeTest.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TestRepository.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/resource/TestRepository.java
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/EmployeeDaoTest.java
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/resource/TestRepositoryTest.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/NgbatisBeanFactoryPostProcessor.java
src/main/java/org/nebula/contrib/ngbatis/binding/DefaultArgsResolver.java
src/main/java/org/nebula/contrib/ngbatis/config/EnvConfig.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasicExt.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java

Closes #216
I tried to cover as much as possible but there are still missing things. Maybe you guys could help. 
* I couldn't run the tests in `/ngbatis-demo` due to a `org.nebula.contrib.ngbatis.exception.QueryException`. Is there a certain config I should do when setting up the project ?
* `BeetlTextRenderTest.test2()` is failing with following exception. Any help with that from your side ? I unfortunately couldn't know where that is originating from.
```java
java.lang.reflect.InaccessibleObjectException: Unable to make public java.lang.Object java.util.Arrays$ArrayList.get(int) accessible: module java.base does not "opens java.util" to unnamed module @50b494a6
```

Draft: Upgrade to jdk 17 and SpringBoot 3.x

---

ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TestRepository.java
ngbatis-demo/src/main/resources/mapper/TestRepository.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NgbatisDemoApplicationTests.java
src/main/java/org/nebula/contrib/ngbatis/config/ParseCfgProps.java
src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
src/main/java/org/nebula/contrib/ngbatis/models/MethodModel.java
src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
src/main/resources/ngbatis-mapper.dtd

For example:
```java
Boolean spaceFromParam(@Param("specifySpace") String specifySpace);
```
```xml
<select id="spaceFromParam" space="${specifySpace}" spaceFromParam="true">
RETURN true;
</select>
```
If the `specifySpace` is not current space, NgBatis will automatically switch.
Can reduce the use of `use space` in ngql.
close: #265

feat: support specify space by param, fix #265

---

CHANGELOG.md
ngbatis-demo/pom.xml
pom.xml
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

Remove unnecessary reflections in transformDateTime, and prevents errors in the millisecond bit in jdk17.
Make the same code applicable to both jdk8 and jdk17 versions, reducing maintenance costs.

fix: remove unnecessary reflections in transformDateTime

---

ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
src/main/resources/NebulaDaoBasic.xml

add new method: listEndNodes
add new test case about listEndNodes

add new method: listEndNodes

---

CHANGELOG.md
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/TestRepository.java
ngbatis-demo/src/main/resources/mapper/TestRepository.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NgbatisDemoApplicationTests.java
src/main/java/org/nebula/contrib/ngbatis/handler/NgSubgraphResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

The scope of bug occurrence: 
- `ResultSetUtil.java`, when `ResultSet` contains Set. ( using `toSet` function )
- `NgSubgraphResultHandler.java`, when `resultType="NgSubgraph"` and toSet is used.
PR type:

fix: the issue of not being able to handle Set type.

---

src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

Sorry, I forgot to check the code style again.😂😂

fix: style check

---

CHANGELOG.md
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/config/Base64PasswordDecoder.java
ngbatis-demo/src/main/resources/application.yml
src/main/java/org/nebula/contrib/ngbatis/NgbatisBeanFactoryPostProcessor.java
src/main/java/org/nebula/contrib/ngbatis/PasswordDecoder.java
src/main/java/org/nebula/contrib/ngbatis/config/NebulaJdbcProperties.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java

Support for #298 
For example:
```java
@Component
public class Base64PasswordDecoder implements PasswordDecoder {
@Override
public String decode(String password) {
return new String(Base64.getDecoder().decode(password));
}
}
```
```yml
nebula:
username: root
password: bmVidWxh # actual password is: nebula
```
At this stage, it is **not** supported to use `@Value` to inject additional attributes.
现阶段 **不** 支持使用 `@Value` 注入额外属性。
PR type:

feat: support the use of ciphertext passwords in yml.

---

ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaBasicDaoTests.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
src/main/resources/NebulaDaoBasic.xml

1、NebulaDaoBasic 的接口拓展shortestOptionalPath()函数，完成查找指定起始点和目的点之间最短路径的功能，允许用户自定义边的类型（Edge type）和方向（direction）
3、增加了对shortestOptionalPath()函数的测试部分代码

feat: shortestOptionalPath() with configurable Edge types and directions to find shortest paths by srcId and dstId

---

CHANGELOG.md
ngbatis-demo/src/main/resources/mapper/DropSpaceDao.xml
pom.xml
src/main/java/org/nebula/contrib/ngbatis/NgbatisBeanFactoryPostProcessor.java
src/main/java/org/nebula/contrib/ngbatis/NgbatisContextInitializer.java
src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
src/main/java/org/nebula/contrib/ngbatis/models/ext/SettableCASignedSSLParam.java
src/main/java/org/nebula/contrib/ngbatis/models/ext/SettableCaSignedSslParam.java
src/main/java/org/nebula/contrib/ngbatis/models/ext/SettableSelfSignedSSLParam.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
src/main/java/org/nebula/contrib/ngbatis/utils/ConfigUtil.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

- nebula-java: 3.6.0 -> 3.8.3
- org.hibernate:hibernate-core was excluded.
> If you need to use hibernate-core, please add the dependency by yourself.
- example:
```yaml
nebula:
pool-config:
enable-ssl: true
ssl-param:
sign-mode: SELF_SIGNED
crt-file-path: /path/to/client.crt
key-file-path: /path/to/client.key
password: password
use-http2: false
custom-headers:
Route-Tag: abc
```

2 fix, 2 dependencies changed, 1 feat. refer to the description for more detail.

---

CHANGELOG.md
README-CN.md
README.md
ngbatis-demo/pom.xml
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Like.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/annotations/DstId.java
src/main/java/org/nebula/contrib/ngbatis/annotations/SrcId.java
src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/KvFn.java
src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

```java
@Data
@Table(name = "like")
public class Like {
@Id // 可选，如果两个节点之间同一类型边的唯一性由源节点id和目标节点id共同决定，可以不加当前属性
private Long rank;
@SrcId // 可选，如果不需要获取关系的源节点id，可以不加当前属性
private String srcId;
@DstId // 可选，如果不需要获取关系的目标节点id，可以不加当前属性
private String dstId;
private Double likeness;
}
```
```java
List<Like> selectEdge();
```
```xml
<select id="selectEdge" resultType=“Like”>
MATCH (n)-[r: like]->(m)
RETURN r;
</select>
```
```java
// 伪代码
like.getSrcId() == id(n)  // true
like.getDstId() == id(m) // true
```

feat: support adding ID attributes of start and end nodes in edge entities

---

CHANGELOG.md
src/main/java/org/nebula/contrib/ngbatis/handler/ObjectResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
src/main/java/org/nebula/contrib/ngbatis/proxy/NebulaDaoBasic.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java
src/test/java/org/nebula/contrib/ngbatis/utils/ReflectUtilTest.java

- fix: Limit the node type obtained by `selectById` to the entity class of the interface.
- fix: When a node has multiple tags, prioritize using the tag of `resultType`. (Collaborate with [charle004](https://github.com/charle004), [#311](https://github.com/nebula-contrib/ngbatis/pull/311))
- fix: debugging log output issue [#312](https://github.com/nebula-contrib/ngbatis/issues/312)
close: #310 #312

When a node has multiple unassociated tags, it supports specifying tag by specifying the resultType

---

src/main/java/org/nebula/contrib/ngbatis/handler/ObjectResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

关键代码如图，执行 transformNode 的时候传入 resultType ，当 tagType 是 nodeType 的 子类时 才去将 nodeType 换成 tagType

解决同一点的Tag实体类相互独立时，映射的Object类型可能发生错误的问题

---

CHANGELOG.md
pom.xml
src/main/java/org/nebula/contrib/ngbatis/NgbatisBeanFactoryPostProcessor.java
src/main/java/org/nebula/contrib/ngbatis/io/DaoResourceLoader.java
src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java

@Space注解值可通过spring配置文件配置
方法：在获取@Space注解name时，通过Spring的 Environment 对象的 resolveRequiredPlaceholders 方法解析配置，同时也兼容固定name的情况。 
使用示例： @Space(name = "${nebula.secondSpace}") ， spring配置文件中若无 nebula.secondSpace 自定义配置则抛出ResourceLoadException
核心改动：

 @Space property configurable supported

---

ngbatis-demo/src/main/resources/application.yml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NgbatisDemoApplicationTests.java
src/main/java/org/nebula/contrib/ngbatis/Env.java
src/main/java/org/nebula/contrib/ngbatis/NgbatisBeanFactoryPostProcessor.java
src/main/java/org/nebula/contrib/ngbatis/SessionDispatcher.java
src/main/java/org/nebula/contrib/ngbatis/config/EnvConfig.java
src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
src/main/java/org/nebula/contrib/ngbatis/session/IntervalCheckSessionDispatcher.java

- Refact and modify the start time of SessionPool.
- Provide a unified way to call scripts for `LocalSession` and `SessionPool`, 
and return them after calling, to reduce the probability of 
not returning after polling and the occurrence of too many connections.
- Provide public network data source for demo.

feat: session pool supports creating through `spaceFromParam`

---

src/main/java/org/nebula/contrib/ngbatis/Env.java
src/main/java/org/nebula/contrib/ngbatis/base/GraphBase.java
src/main/java/org/nebula/contrib/ngbatis/base/GraphBaseExt.java
src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java

as title: 
zh: 为数据对象直接查询的功能，提供在实体注解中指定不同space的支持：
```java
// Both are acceptable. The priority is: Space > Table
// 两种都行，优先级：Space > Table
@Space("test") 
@Table(name = "player", schema="test")
public class Player extends GraphBaseVertex {
// ...
}
```
```java
@Space("${nebula.space}") // from yml or configuration center
@Table(name = "player", schema="${nebula.space}")
public class Player extends GraphBaseVertex {
// ...
}
```

feat: entity direct query supports specifying different spaces.

---

ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/vertex/Player.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/vertex/Team.java
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NgbatisDemoApplicationTests.java
src/main/java/org/nebula/contrib/ngbatis/annotations/base/GraphId.java
src/main/java/org/nebula/contrib/ngbatis/base/GraphBaseExt.java
src/main/java/org/nebula/contrib/ngbatis/base/GraphBaseVertex.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java
src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java

refact: unified primary key annotation.

---

CHANGELOG-CN.md
CHANGELOG.md
README-CN.md
README.md
ngbatis-demo/pom.xml
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Paragraph.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/ParagraphDao.java
ngbatis-demo/src/main/resources/application.yml
ngbatis-demo/src/main/resources/mapper/ParagraphDao.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/NebulaGraphBasicTests.java
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/ParagraphDaoTest.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/Env.java
src/main/java/org/nebula/contrib/ngbatis/NgbatisBeanFactoryPostProcessor.java
src/main/java/org/nebula/contrib/ngbatis/NgbatisContextInitializer.java
src/main/java/org/nebula/contrib/ngbatis/SessionDispatcher.java
src/main/java/org/nebula/contrib/ngbatis/base/GraphBaseExt.java
src/main/java/org/nebula/contrib/ngbatis/config/ParseCfgProps.java
src/main/java/org/nebula/contrib/ngbatis/io/MapperResourceLoader.java
src/main/java/org/nebula/contrib/ngbatis/models/MapperContext.java
src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java
src/main/java/org/nebula/contrib/ngbatis/session/IntervalCheckSessionDispatcher.java
src/main/java/org/nebula/contrib/ngbatis/session/SpaceRouter.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java

- feat: support switching graph space based on parameters for multiple functions.
- refac: Extract the management of space into `SpaceRouter.java`

v2.0.0-beta

---

CHANGELOG-CN.md
CHANGELOG.md
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/AllFieldTypes.java
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/AllFieldTypesDao.java
ngbatis-demo/src/main/resources/mapper/AllFieldTypesDao.xml
ngbatis-demo/src/main/resources/mapper/TestRepository.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/AllFieldTypesDaoTest.java
pom.xml
src/main/java/org/nebula/contrib/ngbatis/Env.java
src/main/java/org/nebula/contrib/ngbatis/binding/DefaultArgsResolver.java
src/main/java/org/nebula/contrib/ngbatis/binding/beetl/functions/ValueFmtFn.java

- fix: fix the issue of `Duration` type in custom xml
- revert: revert the change of 2.0.0-beta.1
> To be compatible with `${ ng.valueFmt( value ) }`, when value is null, it can still output a placeholder. You can use the following method:
>
> ```beetl
> ${ ng.valueFmt( value ) ! "null" }
> ```
>
- fix: fix the issue of field type is Byte, cannot be parsed to entity object.
- upgrade: upgrade fastjson version to 2.0.57.
<details>
<summary><h2> 详情</h2></summary>
- fix: 修复自定义 xml 中， `Duration` 作为属性类型不被支持的问题
- revert: 回退关于 2.0.0-beta.1 的修改。
> 为兼容 `${ ng.valueFmt( value ) }`, 当 value 为 null 时，依然可以输出占位符，可使用以下方式
>
> ```beetl
> ${ ng.valueFmt( value ) ! "null" }
> ```
>
- fix: 修复字段属性为 Byte 时，不能正常解析到实体对象的问题。
- upgrade: 升级 fastjson 版本至 2.0.57.
</details>

fix the mapping issue of `Byte` and `Duration`

---

CHANGELOG-CN.md
CHANGELOG.md
ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/repository/ColumnAliasDao.java
ngbatis-demo/src/main/resources/application.yml
ngbatis-demo/src/main/resources/mapper/ColumnAliasDao.xml
ngbatis-demo/src/test/java/ye/weicheng/ngbatis/demo/repository/ColumnAliasDaoTest.java
src/main/java/org/nebula/contrib/ngbatis/NgbatisContextInitializer.java
src/main/java/org/nebula/contrib/ngbatis/config/NgbatisConfig.java
src/main/java/org/nebula/contrib/ngbatis/handler/ObjectResultHandler.java
src/main/java/org/nebula/contrib/ngbatis/utils/ReflectUtil.java

- Example:
```java
@Table(name = "column_alias")
public class ColumnAlias {
@Id @Column(name = "id_no") private String idNo;
@Column(name = "first_name") private String firstName;
@Column(name = "last_name") private String lastName;
@Transient private String ignoreMe;
}
```
```xml
<select id="propsToObj">
MATCH (n :column_alias)
WHERE n.column_alias.first_name is not null
RETURN
properties(n),
"ignoreMe" as ignoreMe
LIMIT 1
</select>
```

feat: support props can be directly mapped to entity objects.

---

pom.xml

- Relocate 'com.alibaba.fastjson2' to 'org.nebula.contrib.ngbatis.internal.fastjson2' using Maven Shade plugin during build
- This avoids classpath conflicts between fastjson2 (used internally) and fastjson1 which is commonly used in dependent projects
- Enables ngbatis to be integrated safely in environments where both fastjson versions coexist without breaking compatibility or causing runtime errors
- Addresses issue with fastjson version clashes reported by users

fix: use Maven Shade plugin to relocate fastjson2 package in ngbatis
